name: Run tests every hour
on:
  workflow_dispatch:
  schedule:
  - cron: "0 * * * *"

jobs:
  e2e-tests:
    name: Run TestCafe Tests
    runs-on: ${{ matrix.os }}
    outputs:
      outputreport: ${{ steps.testreport.outputs.report }}
      status: ${{ steps.testreport.outputs.status}}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]
    env:
      E2E_URL: 'https://dev.akord.link'
    steps:
      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: latest
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run TestCafe
        run: npm run e2e:headless
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            dist/e2e/test-results.xml
      - id: testreport
        name: Echo report
        run: |
          passed=$(jq -r '.fixtures[].tests[] | select(.errs | length == 0) | .name' dist/e2e/test-results.json)
          failed=$(jq -r '.fixtures[].tests[] | select(.errs | length > 0) | .name' dist/e2e/test-results.json)

          success_emoji=":white_check_mark:"
          fail_emoji=":x:"

          formatted_passed=$(echo "$passed" | sed -e "s/^/$success_emoji /")
          formatted_failed=$(echo "$failed" | sed -e "s/^/$fail_emoji /")

          report="$formatted_passed"$'\n'"$formatted_failed"
          echo "$report"
          
          delimiter="$(openssl rand -hex 8)"
          echo "report<<${delimiter}" >> "${GITHUB_OUTPUT}"
          echo "$report" >> "${GITHUB_OUTPUT}"
          echo "${delimiter}" >> "${GITHUB_OUTPUT}"

          if [ -z "$failed" ]; then
              echo "Tests passed!"
          else
              echo "Tests failed!"
              exit 1
          fi

  send-discord-notification:
    needs: e2e-tests
    runs-on: ubuntu-latest
    if: ${{ failure() }}

    steps:
      - name: Notify Discord on job status
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          content: |
            ${{ needs.e2e-tests.outputs.outputreport }}

  back-to-normal:
    needs: e2e-tests
    runs-on: ubuntu-latest
    if: ${{ success() }}

    steps:
      - name: Check status
        id: check-status
        run: |
          WORKFLOW_ID="79130345"
          TOKEN=${{ secrets.GITHUB_TOKEN }}

          recent_status=$(curl -s -H "Authorization: Bearer $TOKEN" \
            "https://api.github.com/repos/$GITHUB_REPOSITORY/actions/workflows/$WORKFLOW_ID/runs?status=completed&per_page=1&page=1" \
            | jq -r '.workflow_runs[0].conclusion')
          
          echo "$recent_status"
          echo "recent_status::${recent_status}"
      - name: Notify Discord on job status
        uses: tsickert/discord-webhook@v5.3.0
        if: ${{ steps.check-status.outputs.recent_status == 'failure' }}
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          content: |
            Back to normal! Thanks for fixing :heart:

            ${{ needs.e2e-tests.outputs.outputreport }}