name: Run tests every hour
on:
  [push]
  # schedule:
  # - cron: "0 * * * *"

jobs:
  e2e-tests:
    name: Run TestCafe Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        node: [14]
    env:
      E2E_URL: 'https://dev.akord.link'
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run TestCafe
        run: npm run e2e
  send-discord-notification:
    needs: e2e-tests
    runs-on: ubuntu-latest
    if: ${{ always() }}  # Always run this job, regardless of the outcome of the previous job

    steps:
      - name: Notify Discord on job status
        uses: appleboy/discord-action@v0.0.1
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          color: ${{ job.status == 'success' && '00ff00' || 'ff0000' }}