name: Run tests every hour
on:
  [push]
  # schedule:
  # - cron: "0 * * * *"

jobs:
  e2e-tests:
    name: Run TestCafe Tests
    runs-on: ${{ matrix.os }}
    outputs:
      outputreport: ${{ steps.testreport.outputs.report }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]
    env:
      E2E_URL: 'https://dev.akord.link'
    steps:
      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: latest
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run TestCafe
        run: npm run e2e:headless
      - id: testreport
        name: Echo report
        run: echo "report=$(jq -c . dist/e2e/test-results.json)" >> "$GITHUB_OUTPUT"

  send-discord-notification:
    needs: e2e-tests
    runs-on: ubuntu-latest
    if: ${{ needs.e2e-tests.result == 'success' }}  # Always run this job, regardless of the outcome of the previous job

    steps:
      - name: Parse json report
        id: report_to_send
        run: |
          report_json=$(echo ${{ needs.e2e-tests.outputs.outputreport }})
          passed=$(echo "$report_json" | jq -r '.passed')
          total=$(echo "$report_json" | jq -r '.total')
          skipped=$(echo "$report_json" | jq -r '.skipped')
          parsed_report="Passed $passed/$total ($skipped skipped)" 
          echo $parsed_report
          echo "report_to_send=$parsed_report" >> "$GITHUB_OUTPUT"
      - name: Notify Discord on job status
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          raw-data: ${{ needs.e2e-tests.outputs.outputreport }}
          content: "${{needs.send-discord-notification.report_to_send.report_to_send}}"