name: Run tests every hour
on:
  # [push]
  schedule:
  - cron: "0 * * * *"

jobs:
  e2e-tests:
    name: Run TestCafe Tests
    runs-on: ${{ matrix.os }}
    outputs:
      outputreport: ${{ steps.testreport.outputs.report }}
      status: ${{ steps.testreport.outputs.status}}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]
    env:
      E2E_URL: 'https://dev.akord.link'
    steps:
      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: latest
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run TestCafe
        run: npm run e2e:headless
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            dist/e2e/test-results.xml
      - id: testreport
        name: Echo report
        run: |
          failed_scenarios=$(jq -r '.fixtures[].tests[] | select(.errs | length > 0) | .name' dist/e2e/test-results.json)
          passed_scenario=$(jq -r '.fixtures[].tests[] | select(.errs | length == 0) | .name' dist/e2e/test-results.json)
          
          report_json=$(jq -c . dist/e2e/test-results.json)
          
          failed=$(echo "$report_json" | jq -r '.fixtures[].tests[] | select(.errs | length > 0))
          passed=$(echo "$report_json" | jq -r '.passed')
          skipped=$(echo "$report_json" | jq -r '.skipped')
          total=$(echo "$report_json" | jq -r '.total')
          
          parsed_report="FrontEnd Tests: Passed $passed/$total ($skipped skipped)" 
          echo $parsed_report

          success_emoji=":white_check_mark:"
          fail_emoji=":x:"

          formatted_successful_tests=$(echo "$successful_tests" | sed -e "s/^/$success_emoji /")
          formatted_failed_tests=$(echo "$failed_tests" | sed -e "s/^/$fail_emoji /")

          report="$formatted_successful_tests\n$formatted_failed_tests"
          echo $report

          report="$formatted_passed\n$formatted_failed"
          echo "$report"
          
          delimiter="$(openssl rand -hex 8)"
          echo "report<<${delimiter}" >> "${GITHUB_OUTPUT}"
          echo "$report" >> "${GITHUB_OUTPUT}"
          echo "${delimiter}" >> "${GITHUB_OUTPUT}"

          if [ $((passed + skipped)) == $total ]; then
            echo "Tests passed!"
          else
            echo "Tests failed!"
            exit 1
          fi

  send-discord-notification:
    needs: e2e-tests
    runs-on: ubuntu-latest
    if: ${{ failure() }}

    steps:
      - name: Notify Discord on job status
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          content: "${{ needs.e2e-tests.outputs.outputreport }}"
