name: Run tests every hour
on:
  [push]
  # schedule:
  # - cron: "0 * * * *"

jobs:
  e2e-tests:
    name: Run TestCafe Tests
    runs-on: ${{ matrix.os }}
    outputs:
      report: ${{ steps.testcafe.outputs.report }}
    strategy:
      matrix:
        os: [windows-latest]
        node: [14]
    env:
      E2E_URL: 'https://dev.akord.link'
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - id: testcafe
        name: Run TestCafe
        run: npm run e2e:headless && echo "::set-output name=report::$(jq -c . dist/e2e/test-results.json)"
      - name: Echo report
        run: echo $(jq -c . dist/e2e/test-results.json) 

  send-discord-notification:
    needs: e2e-tests
    runs-on: ubuntu-latest
    if: ${{ needs.e2e-tests.result == 'success' }}  # Always run this job, regardless of the outcome of the previous job

    steps:
      - name: Notify Discord on job status
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          raw-data: ${{ fromJson(needs.e2e-tests.outputs.report) }}