name: Run tests every hour
on:
  [push]
  # schedule:
  # - cron: "0 * * * *"

jobs:
  e2e-tests:
    name: Run TestCafe Tests
    runs-on: ${{ matrix.os }}
    outputs:
      report: ${{ steps.testcafe.outputs.report }}
    strategy:
      matrix:
        os: [windows-latest]
        node: [14]
    env:
      E2E_URL: 'https://dev.akord.link'
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - id: testcafe
        name: Run TestCafe
        run: npm run e2e && dist/e2e/test-results.json >> $GITHUB_OUTPUT
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: ${{ always() }}  # Always run this job, regardless of the outcome of the previous job
        with:
          name: JEST Tests
          path: dist/e2e/test-results.xml
          reporter: jest-junit

  send-discord-notification:
    needs: e2e-tests
    runs-on: ubuntu-latest
    if: ${{ always() }}  # Always run this job, regardless of the outcome of the previous job

    steps:
      - name: Notify Discord on job status
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          content: ${{ job.status == 'success' && 'Frontend Tests Success' || 'Frontend Tests Failed' }}