name: Run V2 E2E Tests
on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: 'Test Env'     
        required: true
        options:
          - https://v2.akord.com
        default: https://v2.akord.com
  schedule:
  - cron: "0 0 * * *"

jobs:
  e2e-tests:
    name: Run TestCafe Tests
    runs-on: ${{ matrix.os }}
    outputs:
      outputreport: ${{ steps.testreport.outputs.report }}
      status: ${{ steps.testreport.outputs.status}}
      env_var: ${{ steps.set_env.outputs.E2E_URL }}
    strategy:
      matrix:
        os: [macos-13]
        node: [16]
    steps:
      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: latest
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/checkout@v2
      - name: Add permissions on MacOS
        run: |
          sudo sqlite3 "$HOME/Library/Application Support/com.apple.TCC/TCC.db" "INSERT OR REPLACE INTO access VALUES('kTCCServiceAppleEvents','com.devexpress.testcafe-browser-tools',0,2,3,1,X'fade0c0000000068000000010000000700000007000000080000001443fa4ca5141baeda21aeca1f50894673b440d4690000000800000014f8afcf6e69791b283e55bd0b03e39e422745770e0000000800000014bf4fc1aed64c871a49fc6bc9dd3878ce5d4d17c6',NULL,0,'com.apple.Safari',X'fade0c000000002c00000001000000060000000200000010636f6d2e6170706c652e53616661726900000003',NULL,1687952810);"
          sudo sqlite3 "/Library/Application Support/com.apple.TCC/TCC.db" "INSERT OR REPLACE INTO access VALUES('kTCCServiceScreenCapture','com.devexpress.testcafe-browser-tools',0,2,3,1,X'fade0c0000000068000000010000000700000007000000080000001443fa4ca5141baeda21aeca1f50894673b440d4690000000800000014f8afcf6e69791b283e55bd0b03e39e422745770e0000000800000014bf4fc1aed64c871a49fc6bc9dd3878ce5d4d17c6',NULL,0,'UNUSED',NULL,0,1687952810);"
      - name: Set env
        id: set_env
        run: |
          echo "Setting E2E_URL to v2 url"
          echo "E2E_URL=https://v2.akord.com" >> "$GITHUB_ENV"
          echo "E2E_URL=https://v2.akord.com" >> "$GITHUB_OUTPUT"
      - name: Install dependencies
        run: npm install
      - name: Run TestCafe
        run: npm run e2e:headless-prod
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            dist/e2e/test-results.xml
      - id: testreport
        name: Echo report
        run: |
          passed=$(jq -r '.fixtures[].tests[] | select(.errs | length == 0) | .name' dist/e2e/test-results.json)
          failed=$(jq -r '.fixtures[].tests[] | select(.errs | length > 0) | .name' dist/e2e/test-results.json)

          success_emoji=":white_check_mark:"
          fail_emoji=":x:"

          formatted_passed=$(echo "$passed" | sed -e "s/^/$success_emoji /")
          formatted_failed=$(echo "$failed" | sed -e "s/^/$fail_emoji /")

          report="$formatted_passed"$'\n'"$formatted_failed"
          echo "$report"
          
          delimiter="$(openssl rand -hex 8)"
          echo "report<<${delimiter}" >> "${GITHUB_OUTPUT}"
          echo "$report" >> "${GITHUB_OUTPUT}"
          echo "${delimiter}" >> "${GITHUB_OUTPUT}"

          if [ -z "$failed" ]; then
              echo "Tests passed!"
          else
              echo "Tests failed!"
              exit 1
          fi

  send-discord-notification:
    needs: e2e-tests
    runs-on: ubuntu-latest
    if: ${{ failure() }}

    steps:
      - name: Notify Discord on job status
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          content: |
            Tests failed :broken_heart: [${{ needs.e2e-tests.outputs.env_var }}]
            ${{ needs.e2e-tests.outputs.outputreport }}

  back-to-normal:
    needs: e2e-tests
    runs-on: ubuntu-latest
    if: ${{ success() }}

    steps:
      - name: Check status
        id: check-status
        run: |
          TOKEN=${{ secrets.GITHUB_TOKEN }}
          
          response=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                        "https://api.github.com/repos/${{ github.repository }}/actions/runs")

          previous_run_conclusion=$(echo "$response" | jq -r '.workflow_runs | map(select(.name == "Run V2 E2E Tests")) | .[1] | .conclusion')
          previous_run_id=$(echo "$response" | jq -r '.workflow_runs | map(select(.name == "Run V2 E2E Tests")) | .[1] | .id')

          echo "Previous run $previous_run_id concluded with: $previous_run_conclusion"
          echo "recent_status=$previous_run_conclusion" >> $GITHUB_OUTPUT
      - name: Notify Discord on job status
        uses: tsickert/discord-webhook@v5.3.0
        if: ${{ steps.check-status.outputs.recent_status == 'failure' }}
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          content: |
            Back to normal! Thanks for fixing :metal: [${{ needs.e2e-tests.outputs.env_var }}]
